### ISSUE TITLE
Accessing raw request content in handlers

### ISSUE THREAD

**Issue by pulasthibandara** [sukovanej/effect-http#278]
Hi, thanks for this amazing library. It's effective to use with effect-ts ;)

To perform a signature validation, I need to access the raw string payload of the request, before it gets parsed as JSON. This only needs to be done on a particular route, so I can't do the check across the application. Just wondering if there is a way to access the raw request from the handler?

**Comment by sukovanej** [comment]
I'm afraid, this is currently only available in an extension handler and the extension API will be probably deprecated in favor of the `@effect/platform` middleware anyway. So, unfortunately, you'll need to wait for the current rewrite to be finished or use HTTP from `@effect/platform` directly instead of this library.

**Comment by sukovanej** [comment]
Hey, the rewrite was released. Please, check the [release notes](https://github.com/sukovanej/effect-http/releases/tag/v0.37.0), examples and readme. For your use-case, I think you'll want to use [RouterBuilder.handleRaw](https://sukovanej.github.io/effect-http/modules/RouterBuilder.ts.html#handleraw). Another option is to make a middleware that will check the request path and validate the payload only in case the path matches the one you'd like to validate. With the middleware, you'll be able to keep using `RouterBuilder.handle` and benefit from the automatic validation.
