### ISSUE TITLE
Replace Express with Hattip for server

### ISSUE THREAD

**Issue by jessekelly881** [sukovanej/effect-http#34]
While I really like the way that servers are defined in this library, the use of express is somewhat annoying. Especially for people interested in using this with edge/lambda functions. [Hattip](https://github.com/hattipjs/hattip) is probably a better target for this sense it abstracts away the request handler and is compatible with other frameworks besides express(e.g. aws lambda, etc.). Also, express is also a bit dated at this point and Hattip uses more modern js apis.

**Comment by sukovanej** [comment]
Yeah, agree. I want to move the code dealing with request handling from express module to the server and make the express integration pluggable. Having the http library just a thin adapter will enable other libraries to be used instead by implementing an adapter for effect-http. I'll try to prepare the hattip as the first example adapter during the weekend.

**Comment by sukovanej** [comment]
I did some changes that should enable easier pluggability of different libs but it's still not 100% done. Because there are still plenty of essential stuff to be resolved, I decided to not focus on the hattip integration right now.

But at least I created a little example scretching the possible implementation - [check this repo](https://github.com/sukovanej/effect-http-hattip-example). The idea is similar to express implementation, it's just a function `Server -> HattipHandler`. It is definitely not production ready but if you want, you can try playing with it yourself. To get it into the production state one'd need to probably change it to `Server -> Effect ? ? HattipHandler` to propagate the runtime and deal correctly with interuptions.

BTW, I like the idea of using the Fetch API `Response` and `Request` objects, I need to dig deeper but I'm thinking I replace my custom objects with those. Therefore, the derivation of hattip handler might become really trivial in the future as it uses this interface as well.

**Comment by jessekelly881** [comment]
Awesome! I'll play around with the adaptor you wrote. Going with Response and Request objects would be convenient. If you go down this route, you may be able to piggyback on hattip to create other integrations(for express, et al). Hattip adaptors, fundamentally, just allow you to take a function `HattipHandler  = Request -> Response` and use it in whatever framework you want. Otherwise, you might end up just rewriting a lot of the adaptors that hattip already provides.

**Comment by sukovanej** [comment]
I like that. I'll definitely consider it 👍

**Comment by sukovanej** [comment]
After recent changes, result of [Server.buildServer](https://sukovanej.github.io/effect-http/modules/Server.ts.html#buildserver) is a structure containing the handler `(request: Request) => Effect.Effect<R, ApiError, Response>` and an information about the endpoint. Therefore, the [express](https://github.com/sukovanej/effect-http/blob/master/src/Express.ts) implemetation is really a thin layer to run the server. Hattip could be probably implemented in a similar manner. 

Currently, my plan for effect-http is to get rid of the express, wait for [@effect/platform](https://github.com/Effect-TS/platform) and implement the server runtime using it. I'm gonna close this issue for now. If anybody decided to implement the hattip derivation as a standalone package, feel free to ping me for support.

**Comment by jessekelly881** [comment]
Sounds good! Thanks @sukovanej. I will take a look ar maybe implementing it now that the internals have been updated.
