### ISSUE TITLE
Feature Request: Optional Security Scheme

### ISSUE THREAD

**Issue by TylorS** [sukovanej/effect-http#481]
I've been continuing to work on a [Realworld](https://realworld-docs.netlify.app/docs/specs/frontend-specs/swagger/) example application for Typed. Some endpoints will make slightly different queries to the database given if there is a current user or not. For example, if a current user is available, articles return whether or not the user favorited the article, or if they follow the author of the article. 

The one thing I've stumbled across so far is that I can't define a route which has been the ability to specify optional security schemes.

I'm not as familiar with the internal of how everything comes together, but I could kind of see at least a few different APIs that could make sense. I'd love to hear your thoughts as well

#### Follow a little more closely to the OpenAPI Spec

I think we'd just need to allow the ability for all of the `SecurityScheme` fields to be optional

```ts
export const jwtToken: SecurityScheme<*> = {
  type: "http",
  options: {
    scheme: "bearer"
  },
  schema: ...
}

Api.get(..., ..., ..., { security: {  jwtToken, none: {}  }  })
```

I suspect staying close to that of the OpenAPI may help with generating the appropriate output, and will probably do better when your endpoint has more than 1 security scheme using an `OR` style relationship. 

##### Variation

Maybe we be a bit more explicit as well, as it's hard to type an empty object in TS, and would be easier to create a discriminated union type across

```ts
Api.get(..., ..., ..., { security: {  jwtToken, none: { type: "none" }  }  })
``` 

#### Extend the current SecuritySchema

In this variant, I'd see adding an `optional: boolean` flag to the existing `SecurityScheme` type. I guess I'd intuit that with `optional:true`, your Schema would be wrapped in something like sort of nullish/optional type.

I don't know this is great when it comes to generation, because I think it'd require de-duplicating multiple `optional: true` schemes to map to a single "empty" entry in the OpenAPI specification. I'd also assume building and validating that schema would be more costly at runtime as well.

### Ancillary thought

I don't have a real use-case for this stuff, but I think that the current definitions of security are more limited than that of OpenAPI itself. As I hinted, hopefully correctly, in the first variant, today we can we can only define `OR` style relationships between security schemes, but in the specification its also possible to specify `AND` style relationships. I don't see this as necessary for my own use cases, but I suspect it'll be asked for at some point.

I could see this happening a few different ways in itself, but I feel like just adding the ability for non-empty arrays as values in the security record would open the way up to AND relationships. 

It'd all culminate to something like the following

```ts
Api.get(........., { security: {  one: [ A, B ], two: [ A, C ], three: D, none: {}  } })
```

In a case where there is an `AND` style relationship, I would generally expect the same shape to be available when writing your handler functions

```ts
RouterBuilder.handle('opId', ({...}, { one: [aType, bType] }) => ...) 
```

A slight variation of this would be to accept a record instead of tuples, and I'd expect similar rules to apply in that case as well.

```ts
Api.get(........., { security: {  one: {a: A, b: B } , two: { a: A, c: C }, three: D, none: {}  } })

RouterBuilder.handle('opId', ({...}, { one: {a: aType, b: bType } }) => ...) 
```

**Comment by sukovanej** [comment]
Hmm, right now I'm actually thinking about generalising the whole security machinery. This is a long shot and random idea but maybe instead of `SecuritySchema<A>` we could have `Security<A, E, R>`, a generally effectful computation that'd take a server request and would produce an output `A` (representing the user information, potentially enhanced by data from a storage or whatever, the options are limitless with this generalisation I guess). Also, it would specify a declaration of the schema (probably something similar we have right now) so we can still derive the OpenAPI spec. With this representation, we probably have canonical instances of an Alternative and Product, so we'd expose `Security.orElse`, `Security.flatMap`, etc. combinators, thus gaining the ability to compose the security even more generally than using `and` and `or`-like API.

You're use-case solution might look something like this

```ts
const ignoredSecurity = Security.make(...)

const mySecurity = pipe(
  Security.bearer(...),
  Security.orElse(() => ignoredSecurity),
)
```

It'd need a lot of experimentation ofc but I like the sound of it. WDYT?

**Comment by TylorS** [comment]
Closing this now that Security supports both and + or relationships
